#!/bin/bash
set -e

CURDIR="$(pwd)"

if [ ! -d rt ]; then
	python3 -m virtualenv rt
fi

write_launch_script() {
	local pyname="$1"
	local tofile="$2"
	cat > "$tofile" << EOF
#!/bin/bash
"${CURDIR}/rt/bin/python3" "${CURDIR}/${pyname}" "\$@"
EOF
}

if [ -n "$1" ]; then
	mkdir -p dist
	printf "%s\n" "$@" \
	| while read -r pyname; do
		tofile="dist/$(basename "$pyname" .py)"
		write_launch_script "$pyname" "$tofile"
		chmod u+x "$tofile"
	done
fi
